version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: nestapi
      POSTGRES_PASSWORD: nestapi
      POSTGRES_DB: nestapi
    networks:
      - nest-api-network
networks:
  nest-api-network:
# cli -> docker compose up dev-db -d
# note: needs to have the docker desktop running.
